[package]
name = "punch"
version = "0.1.0"
authors = ["David Allen <david.allen@columnzero.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories = "3.0.1"
chrono = "0.4"
